### ISSUE TITLE
Schätzung der Epics und Aufbau einer Roadmap

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Wahllokalsystem#11]
- [x] Schätzung aller Epics im Verhältnis zu einer einander die für die Kodierung relevant sind (via Epic-Points in Zenhub)
- [x] Ableiten einer Roadmap wann ungefähr welcher Teil bearbeitet werden kann und Beachtung der verfügbaren Personen
- [x] Readme-Abschnitt zu Roadmap entsprechend aktualisieren
