### ISSUE TITLE
Erstellung API

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Wahllokalsystem#151]
# Akzeptanzkriterien
- [x] öffentliche API beschrieben
  - Operationen und Model ist erkennbar
  - Model umfasst neben Datentypen auch Einschränkungen (z.B. not Null)
- [x] OpenApiSpec ist vorhanden

# Umsetzungshinweise
- separates Modul

# Todos
- [x] ResponseStatus verifiziert
- [x] Sollen ResponseEntities verwendet werden?
  - aktuell nicht notwendig wird erst mit der Einführung weitere Statuswerte erforderlich oder mit der Implementierung
- [x] Ist es korrekt das an einigen Stellen Listen anstelle von Sets verwendet werden?
  - an folgenden Stellen:
    - Ergebnismeldung
    - WahldatenController
  - [x] #276
- [x] Doku erweitern wie man aus der API einen Client macht
  - -> ich bin der Meinung der Commit e23f37334d7a5c2b77ba79c00c7d7408be640af9 zeigt alles was man braucht
- [x] Stimmt es dass einige identifikator-Felder optional sind?
  - Betrifft Wahl in getWahlen und in Basisstrukturdaten
  - id der ReferendumOption in getReferendumByWaldIDWahlbezirkID
- [X] Wie wäre es mit Optional bei Optionalen werten anstelle von Markierung mit NotNull?
  - kein Optional: ich sehe hier nicht den Vorteil. Anstelle von `!= null` prüft man dann mit `isEmpty()`
  - https://stackoverflow.com/questions/23454952/uses-for-optional in Kombination mit https://nipafx.dev/design-java-optional/
  - wir müssen mit den Returns des Controllers nicht arbeiten, daher kein Optional als Return
  - die DefaultImplementierung wird ein Mapper sein auf ein Persisitierungsmodell. Daher sehe ich keine Vorteile in Optionals da es keine relevante Logik gibt.

**Comment by MrSebastian** [comment]
Kann man das Model in subpackages aufteilen zur Steigerung der Übersicht?

**Comment by MrSebastian** [comment]
Wie wäre es mit Optional bei Optionalen werten anstelle von Markierung mit NotNull?

**Comment by MrSebastian** [comment]
Ist es korrekt das an einigen Stellen Listen anstelle von Sets verwendet werden?

**Comment by MrSebastian** [comment]
Stimmt es dass einige `identifikator`-Felder optional sind?
