### ISSUE TITLE
Bereitstellung LOGIN-Pages

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Wahllokalsystem#173]
# Akzeptanzkriterien
- [x] Wahllokalsystem-LoginGUI wird ausgeliefert
- [x] Admin-LoginGUI wird ausgeliefert

# Umsetzungshinweise
- unter Beachtung relevanter Filter (CORS, Csrf, ...)
- siehe MainController, templates und `wro`
```[tasklist]
### Tasks
- [x] get csrf token into form
- [x] JS-Error: $(...).popover is not a function at /js/checkCapslock.js:8
- [x] Admin-Monitoring-Tool-Login: Checkboxen fehlen
- [x] error Darstellung verifizieren
```

**Comment by Nic12345678** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wahllokalsystem-65e732175da7e1141c666b0d/issues/it-at-m/Wahllokalsystem/173?planning-poker) with Zenhub @vjohnslhm

**Comment by Nic12345678** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wahllokalsystem-65e732175da7e1141c666b0d/issues/it-at-m/Wahllokalsystem/173?planning-poker) with Zenhub @dragonfly28 @GerhardPx @MrSebastian @vjohnslhm
