### ISSUE TITLE
Implementierung Login-Logik

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Wahllokalsystem#175]
# Akzeptanzkriterien
- [x] Login über Login-GUIs funktioniert
  - Erfolg mit korrekten Credentials
  - Misserfolg bei inkorrekten Credentials
- [x] Authentifizierung und Authorisierung
  - unter Verwendung von LDAP zur Authentifizierung
- [x] Update LoginVersuche
- [x] Übersicht über Sessions
- [x] Invalidierung von Sessions

# Umsetzungshinweise
- Informationen über den aktuellen Wahltag kommen vom Info-Management-Service
```[tasklist]
### Tasks
- [x] Implementierung Sessession-Management (beachte alten SessionController) #590
- [x] Anbindung der korrekten Userverwaltung (DB + LDAP)
- [x] Erstellung einer simplen FrontendAnwendung zur Verifikation (lokal und Zugriff auf einen Service) - prototyisch gemacht auf Branch `connect fe with authservice`
- [x] Prüfung der Implementierung Authorisierung #645
- [x] Implementierung Authorization-Server #603
- [x] Update der Login-Attempts (in Review-> MrSebastian #585)
- [x] Ergänzung der Tests um eine Testmethode zur Verifizierung der Entstehung der Session in der Tabelle "SPRING_SESSION" und des SessionAttributes "SPRING_SECURITY_SAVED_REQUEST" in der Tabelle "SPRING_SESSION_ATTRIBUTES" nach dem gelungenen Login als Integration-Test.
```

**Comment by MrSebastian** [comment]
`- [ ] LDAP-Service in Docker-Compose enthalten` entfernt da es einen embedded LDAP-Server gibt der aus meiner Sicht das Ziel ebenfalls unterstützt aber weniger Komplex ist als über Container zu gehen. Haupnachteil ist dass man zur Laufzeit keine Plege betreiben kann, aber dass sollte kein Problem darstellen.
