### ISSUE TITLE
Bereitstellung von Testtools in wls-common

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Wahllokalsystem#255]
# Beschreibung

In den verschiedenen Services kam bereits mehrfach die Klasse `SecurityUtils` zum Einsatz mit deren Hilfe der SecurityContext konfiguriert werden kann.

Dadurch das die Klasse in diversen Services zum Einsatz kommt schlage ich vor diese zentral in wls-common zur Verfügung zu stellen. Es sollte ein neues Modul (testing) erstellt werden. Diese Dependency wird in den Services im Testscope verwendet.

Als Bestandteil sehe ich aktuell [SecurityUtils](https://github.com/it-at-m/Wahllokalsystem/blob/93a1b381278eb435b34acfd7760b86d8925c19e4/wls-wahlvorbereitung-service/src/test/java/de/muenchen/oss/wahllokalsystem/wahlvorbereitungservice/utils/SecurityUtils.java)

# Todo
- [x] Erstellung neues Modul in wls-common -> #293 
- [x] Erstellung Utils-Klasse im neuen Modul -> #293 
- [x] Planung neues Release von wls-common
  - Zusammen mit #254 nach Abschluss der PRs:
    - #300
    - #293 
- [x] Planung Verwendung in bestehenden Services
  - #294
  - #295
  - #296
  - #297

**Comment by MrSebastian** [comment]
@GerhardPx @dragonfly28 @Nic12345678 wie seht ihr das? Gerne entsprechend reacten.

**Comment by MrSebastian** [comment]
runWith für [authorities] verwenden

**Comment by MrSebastian** [comment]
blocked: Warten auf Abschluss von PRs bevor Release erstellt wird:
- #300
- #293
