### ISSUE TITLE
Erstellung Grundlagen für Frontendentwicklung

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Wahllokalsystem#460]
In der Phase 2 wollen wir die Entwicklung des Frontends vollziehen. Zuerst soll das Frontend für die Bundestagswahl 2025 erstellt werden. Beginnen soll die Phase 2 im Januar 2025. Um möglichst effiziente beginnen zu können sollen Grundlagen in Form eines technischen Durchstiches gemacht werden.

Dieser soll folgende Funktionen anbieten:

- [x] es gibt ein Projekt auf Basis des Archetypes für das Frontend
- [x] es git Workflows
  - [x] zur Sicherstellung der Qualität
  - [x] zur Bereitstellung eines Images für ein Deployment
- [x] die Offlinefähigkeit ist Exemplarisch implementiert
- [x] es gibt exemplarische Kommunikation mit dem Backend
- [x] das Frontend ist in die Security eingebunden
- [x] Es gibt exemplarische Tests
- [x] die Architektur ist grundlegend Beschrieben
  - z.b. Store

**Comment by MrSebastian** [comment]
- [ ] Sollen wir aus dem Issue vielleicht ein Epic machen?
- [ ] Sollen wir einen Release definieren dem wir die entsprechenden Tätigkeiten zuordnen?
- [ ] Milestone wäre aus meiner Sicht weiterhin die Phase 1

**Comment by Nic12345678** [comment]
> * [ ]  Sollen wir aus dem Issue vielleicht ein Epic machen?
> 
>     * [ ]  Sollen wir einen Release definieren dem wir die entsprechenden Tätigkeiten zuordnen?
> 
>     * [ ]  Milestone wäre aus meiner Sicht weiterhin die Phase 1

Ich wäre für ein Epic. Release definieren, nicht unbedingt. Milestone Phase 1 - ja.

**Comment by vjohnslhm** [comment]
@MrSebastian und ich haben uns geeinigt, dass das Epic und die Issues zu keinem Milestone oder Release zugeordnet werden.
Die Issues werden diesem Epic untergeordnet, und - wenn in Bearbeitung - dem jeweiligen Sprint zugeordnet.

**Comment by vjohnslhm** [comment]
alle issues sind abgeschlossen
