### ISSUE TITLE
Ergänzen der `@ApiResponses`-Annotation

### ISSUE THREAD

**Issue by vjohnslhm** [it-at-m/Wahllokalsystem#622]
>  @vjohnslhm 
> 
> > Was mir nebensächlich noch aufgefallen ist: Bei den anderen Services gibt es im Controller noch die @ApiResponses-Annotation mit den Swagger-Beschreibungen zu den verschiedenen ResponseCodes, das gibt es hier nicht. Sollten die (ggf in einem neuen Issue) noch ergänzt werden?
> 
> Ja bitte. Gute Idee damit wir das einheitlich haben. Über die SwaggerConfiguration kann man dies auch zentral für alle Controller eines Services definieren.

_Originally posted by @MrSebastian in https://github.com/it-at-m/Wahllokalsystem/issues/613#issuecomment-2522739353_
            
Alle Services sollten dafür nochmal durchgeschaut werden und die ApiResponses entsprechend hinzugefügt, ausgelagert oder fehlende ergänzt werden. 

### Akzeptanzkriterien:
- [ ] Die 4xx und 5xx Stati sind in allen Services global in `SwaggerConfiguration.java` definiert (Beispiel siehe [EAI-Service](https://github.com/it-at-m/Wahllokalsystem/blob/4b9907d71d1851c1dadbfad38ef28bf0064ce51f/wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/configuration/SwaggerConfiguration.java#L53-L90))
- [ ] Individuelle Stati (wie zB `204`) sind im entsprechenden Controller definiert
- [ ] Alle Statusbeschreibungen haben den gleichen Text

```[tasklist]
### Tasks
- [ ] Admin Service
- [ ] Auth Service
- [ ] Basisdaten Service
- [ ] Briefwahl Service
- [ ] Broadcast Service
- [ ] EAI Service
- [ ] Ergebnismeldung Service
- [ ] Infomanagement Service
- [ ] Monitoring Service
- [ ] Vorfälle und Vorkommnisse Service
- [ ] Wahlvorbereitung Service
- [ ] Wahlvorstand Service
```

**Comment by MrSebastian** [comment]
Wir sollten zusammentragen auf welche Kriterien jeder Service geprüft werden soll und dies dann explizit als Kriterien definieren.

**Comment by vjohnslhm** [comment]
In dem Zug könnten auch die Beschreibungstexte vereinheitlicht werden.
Beispiel:
![grafik](https://github.com/user-attachments/assets/413cdc3c-d801-41fc-a3d0-f4faf46ab8e3)
![grafik](https://github.com/user-attachments/assets/7eb02dd8-2c37-4b29-ba08-2a02ef23fd2d)

**Comment by MrSebastian** [comment]
CodeRabbit hat das Problem auch angemerkt: https://github.com/it-at-m/Wahllokalsystem/pull/621#discussion_r1873293132

**Comment by vjohnslhm** [comment]
Ergebnis der kurzen Absprache: Am Beispiel vom [EAI-Service](https://github.com/it-at-m/Wahllokalsystem/blob/4b9907d71d1851c1dadbfad38ef28bf0064ce51f/wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/configuration/SwaggerConfiguration.java#L53-L90) sollen 4xx und 5xx Codes global in der SwaggerConfiguration definiert werden. alle anderen werden konkret in den einzelnen Controllern der jeweiligen Services angegeben.

**Comment by MrSebastian** [comment]
@DanielOber Kann es sein dass das Issue erledigt ist. Ich sehe zahlreiche PRs.

**Comment by MrSebastian** [comment]
Die PRs könntest du in Zenhub noch zu dem Issue connecten

**Comment by DanielOber** [comment]
Issue closed, wurde in den ganzen PRs alles erfolgreich erledigt.
