### ISSUE TITLE
Keycloak durch AuthService ersetzen

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Wahllokalsystem#645]
Als Entwickler möchte ich den Keycloak durch den AuthService ersetzen um die Zielarchitektur korrekt abzubilden.

# Akzeptanzkriterien
- [x] Es wird kein Keycloak mehr verwendet oder bereitgestellt
- [x] Anfragen die unter Verwendung des Keycloak arbeiteten müssen mit dem Auth-Service arbeiten
  - [x] alle Rechte sind in Keycloak vorhanden
  - [x] `wls_all`, `wls_all_ubw` und `wls_all_bwb` sind mit allen Rechten ausgestattet die sich auch in Keycloak hatten

# Tasks
- [ ] Erweiterungen Auth-Service mit Rechten über Flyway in den regulären migrationen
- [ ] ldif ist um die Benutzer erweitert
- [ ] Mock und OAuth2 Security ist verfügbar jeweilis mit allen URLs: https://www.jetbrains.com/help/idea/oauth-2-0-authorization.html
- [ ] Requests umgestellt auf Security-Settings
